### PR TITLE
corrected typo

### PR DESCRIPTION
**Pull request by michael-biz**

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks, this will be a breaking change :(.

**Comment by michael-biz** [comment]
One way to avoid this breaking change would be to keep the version with the typo and add the new correct one as an alias.

**Comment by NetanelBasal** [comment]
Great idea.

**Comment by NetanelBasal** [comment]
Waiting for your fix.

**Comment by NetanelBasal** [comment]
Can you check the tests, please?

**Pull request merged**
