### PR TITLE
Added String.prototype.includes polyfill for IE 11

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
Fixes https://github.com/NetanelBasal/ngx-auto-unsubscribe/issues/5

@NetanelBasal Could you merge this PR and release a new version? So I can fix our prod site...

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Maybe it will be better to change the code to use `indexOf`?

**Comment by BorntraegerMarc** [comment]
@NetanelBasal good idea. Will you provide a fix?

**Comment by NetanelBasal** [comment]
Yes, I'll fix it tonight and update the version. Thanks. I will let you know.

**Comment by NetanelBasal** [comment]
Fix in 1.0.1. Thanks.

**Pull request closed without merging**
